services:
  db:
    image: postgres:16-alpine
    container_name: cafeteria_db
    environment:
      POSTGRES_DB: cafeteria_up
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ajstyles2006
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/reports_vw.sql:/docker-entrypoint-initdb.d/02-reports_vw.sql
      - ./db/indexes.sql:/docker-entrypoint-initdb.d/03-indexes.sql
      - ./db/roles.sql:/docker-entrypoint-initdb.d/04-roles.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/05-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cafeteria_up"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./api-u1
      dockerfile: Dockerfile
    container_name: cafeteria_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: cafeteria_up
      DB_USER: postgres
      DB_PASSWORD: ajstyles2006
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
