services:
  db:
    image: postgres:16-alpine
    container_name: cafeteria_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/reports_vw.sql:/docker-entrypoint-initdb.d/02-reports_vw.sql
      - ./db/indexes.sql:/docker-entrypoint-initdb.d/03-indexes.sql
      - ./db/roles.sql:/docker-entrypoint-initdb.d/04-roles.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/05-seed.sql
      - ./db/migrate.sql:/docker-entrypoint-initdb.d/06-migrate.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./api-u1
      dockerfile: Dockerfile
    container_name: cafeteria_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${APP_DB_USER}
      DB_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
